# Generated by Django 5.1.7 on 2025-03-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Ticket_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Movie_name', models.CharField(max_length=30)),
                ('Ticket_Amt', models.IntegerField()),
                ('cust_no', models.IntegerField()),
                ('cust_name', models.CharField(max_length=30)),
            ],
        ),
    ]
